<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.U1Jc.Rj' shared service.

return $this->privates['.service_locator.U1Jc.Rj'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'categoryName' => ['privates', '.errored..service_locator.U1Jc.Rj.App\\Entity\\Category', NULL, 'Cannot autowire service ".service_locator.U1Jc.Rj": it references class "App\\Entity\\Category" but no such service exists.'],
]);
