<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.fWA5iP6' shared service.

return $this->privates['.service_locator.fWA5iP6'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'article' => ['privates', '.errored..service_locator.fWA5iP6.App\\Entity\\Article', NULL, 'Cannot autowire service ".service_locator.fWA5iP6": it references class "App\\Entity\\Article" but no such service exists.'],
    'slugify' => ['privates', 'App\\Service\\Slugify', 'getSlugifyService.php', true],
]);
