<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'App\Service\Slugify' shared autowired service.

include_once $this->targetDirs[3].'/src/Service/Slugify.php';

return $this->privates['App\\Service\\Slugify'] = new \App\Service\Slugify();
