<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container090gw0f\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container090gw0f/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container090gw0f.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container090gw0f\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \Container090gw0f\srcApp_KernelDevDebugContainer([
    'container.build_hash' => '090gw0f',
    'container.build_id' => 'e0cac435',
    'container.build_time' => 1558707124,
], __DIR__.\DIRECTORY_SEPARATOR.'Container090gw0f');
