<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerS5tJxSh\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerS5tJxSh/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerS5tJxSh.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerS5tJxSh\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerS5tJxSh\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'S5tJxSh',
    'container.build_id' => '4b1758b0',
    'container.build_time' => 1559053756,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerS5tJxSh');
